etc/check_mk/main.mk
etc/check_mk/conf.d/README
var/lib/check_mk/autochecks
var/lib/check_mk/cache
var/lib/check_mk/counters
var/lib/check_mk/logwatch
var/lib/check_mk/packages
var/lib/check_mk/precompiled
usr/bin/check_mk
usr/share/check_mk/checks
usr/share/check_mk/checks-man
usr/share/check_mk/modules
usr/share/check_mk/pnp-templates
usr/share/check_mk/notifications
usr/share/check_mk/agents/special/* /usr/share/check_mk/special
