.TH waitmax 1 "March 2008" "waitmax 1.1" "User commands"
.SH NAME
waitmax \- allow program to run at most a specified amount of time
.SH SYNOPSIS
.B waitmax
[\|\-s
.IR signum \|]
.I maxtime
.I programm
[\|
.IR args\&.\|.\|. \|]

.SH DESCRIPTION
.B waitmax
executes
.I program
in a new process. If that process
does not exit within at most
.I maxtime
seconds, it is being killed with signal TERM.

.SH OPTIONS
.TP
.B \-s, \-\-signal \fIsignum\fP
Use \fIsignum\fP to kill the program instead of TERM.
.TP
.B \-h, \-\-help
Show short help and exit.
.TP
.B \-V, \-\-version
Show version and exit.

.SH "EXIT VALUES"

.PP
.IP "\fB255\fP"
The program has been signalled and terminated, because
the time has elapsed, before the program has exited itself.
.IP "\fB254\fP"
The program has exited neither by signal nor
normally. Strange. This should never happen.
.IP "\fB253\fP"
The program couldn't be executed.
.IP "\fB128\fP+\fIsignum\fP"
The program has terminated with
signal \fIsignum\fP \fBbefore\fP the time has elapsed (not
by waitmax, but by itself or some other process).
.IP "\fB1\fP"
Waitmax has been called with illegal options.

.SH CREDITS
Many thanks to Jürgen Kuchenbecker, who had the idea of
writing such a program and who assisted me in coding and
testing it.

.SH AUTHOR
waitmax was written by Mathias Kettner. The most current source code
is located at http://mathias-kettner.de/waitmax.html.
